import 'package:money_mate/models/models.dart';

List<Asset> topAssets = [
  Asset(name: 'Bitcoin', symbol: 'BTC', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Ethereum', symbol: 'ETH', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Binance Coin', symbol: 'BNB', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Cardano', symbol: 'ADA', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Coti', symbol: 'COTI', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'XRP', symbol: 'XRP', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Dogecoin', symbol: 'DOGE', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Polkadot', symbol: 'DOT', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Litecoin', symbol: 'LTC', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Chainlink', symbol: 'LINK', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Stellar', symbol: 'XLM', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Polygon', symbol: 'MATIC', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'THETA', symbol: 'THETA', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'VeChain', symbol: 'VET', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Filecoin', symbol: 'FIL', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'TRON', symbol: 'TRX', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'EOS', symbol: 'EOS', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Neo', symbol: 'NEO', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Aave', symbol: 'AAVE', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Cosmos', symbol: 'ATOM', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Klaytn', symbol: 'KLAY', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Tezos', symbol: 'XTZ', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Maker', symbol: 'MKR', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Compound', symbol: 'COMP', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Algorand', symbol: 'ALGO', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Decred', symbol: 'DCR', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Dai', symbol: 'DAI', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'IOTA', symbol: 'MIOTA', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Zcash', symbol: 'ZEC', amount: 0.0, buyingPrice: 0.0),
  Asset(name: 'Waves', symbol: 'WAVES', amount: 0.0, buyingPrice: 0.0),
  // Add more assets here
];
