import 'package:money_mate/models/models.dart';

List<Asset> topAssets = [
  Asset(id: 'bitcoin', name: 'Bitcoin', symbol: 'BTC', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'ethereum', name: 'Ethereum', symbol: 'ETH', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'binancecoin', name: 'Binance Coin', symbol: 'BNB', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'cardano', name: 'Cardano', symbol: 'ADA', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'coti', name: 'Coti', symbol: 'COTI', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'ripple', name: 'Ripple', symbol: 'XRP', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'dogecoin', name: 'Dogecoin', symbol: 'DOGE', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'polkadot', name: 'Polkadot', symbol: 'DOT', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'litecoin', name: 'Litecoin', symbol: 'LTC', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'chainlink', name: 'Chainlink', symbol: 'LINK', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'stellar', name: 'Stellar', symbol: 'XLM', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'matic-network', name: 'Polygon', symbol: 'MATIC', amount: 0.0, buyingPrice: 0.0), // Corrected
  Asset(id: 'theta-token', name: 'THETA', symbol: 'THETA', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'vechain', name: 'VeChain', symbol: 'VET', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'filecoin', name: 'Filecoin', symbol: 'FIL', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'tron', name: 'TRON', symbol: 'TRX', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'eos', name: 'EOS', symbol: 'EOS', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'neo', name: 'Neo', symbol: 'NEO', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'aave', name: 'Aave', symbol: 'AAVE', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'cosmos', name: 'Cosmos', symbol: 'ATOM', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'klay-token', name: 'Klaytn', symbol: 'KLAY', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'tezos', name: 'Tezos', symbol: 'XTZ', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'maker', name: 'Maker', symbol: 'MKR', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'compound-governance-token', name: 'Compound', symbol: 'COMP', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'algorand', name: 'Algorand', symbol: 'ALGO', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'decred', name: 'Decred', symbol: 'DCR', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'dai', name: 'Dai', symbol: 'DAI', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'iota', name: 'IOTA', symbol: 'MIOTA', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'zcash', name: 'Zcash', symbol: 'ZEC', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'waves', name: 'Waves', symbol: 'WAVES', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'ethereum-classic', name: 'Ethereum Classic', symbol: 'ETC', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'uniswap', name: 'Uniswap', symbol: 'UNI', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'wazirx', name: 'WazirX', symbol: 'WRX', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'ftx-token', name: 'FTX Token', symbol: 'FTT', amount: 0.0, buyingPrice: 0.0),
  Asset(id: 'truefi', name: 'TrueFi', symbol: 'TRU', amount: 0.0, buyingPrice: 0.0),
];
